version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: testcontainer
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
            - "82:82"
    networks:
      - webnet
networks:
  webnet:
